name: imagebuilderç¼–è¯‘24.10.4
on: 
  workflow_dispatch:
  repository_dispatch:
    types:
      - Tag_updated
  schedule:
  - cron: "20  4 * * 1"

env:
  TZ: Asia/Shanghai


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - name: åˆ é™¤æ–‡ä»¶
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"



    - name: æ˜¾ç¤ºç³»ç»Ÿæƒ…å†µ
      run: |
        lscpu
        free -h
        df -Th
        uname -a
        echo "TIME1=$(date "+%Yå¹´%mæœˆ%dæ—¥%Hæ—¶%Måˆ†")" >> $GITHUB_ENV

    - name: å®‰è£…ä¾èµ–æ–‡ä»¶
      run: |
        sudo -E apt update -y
        sudo -E apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
        mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
        libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip zstd \
        vim wget xmlto xxd zlib1g-dev python3-setuptools

    - name: ä¸‹è½½imagebuilderæºç 
      run: |
        wget https://downloads.immortalwrt.org/releases/24.10.4/targets/x86/64/immortalwrt-imagebuilder-24.10.4-x86-64.Linux-x86_64.tar.zst
        tar -I zstd -x -f immortalwrt-imagebuilder-24.10.4-x86-64.Linux-x86_64.tar.zst
        

    - name: ä¿®æ”¹é…ç½®å’Œç¼–è¯‘æ–‡ä»¶
      run: |
        cd immortalwrt-imagebuilder-24.10.4-x86-64.Linux-x86_64
        sed -i 's/CONFIG_TARGET_ROOTFS_EXT4FS=y/#CONFIG_TARGET_ROOTFS_EXT4FS is not set/' .config
        sed -i 's/CONFIG_TARGET_EXT4_RESERVED_PCT=0/#CONFIG_TARGET_EXT4_RESERVED_PCT=0 is not set/' .config
        sed -i 's/CONFIG_TARGET_EXT4_BLOCKSIZE_4K=y/#CONFIG_TARGET_EXT4_BLOCKSIZE_4K is not set/' .config
        sed -i 's/CONFIG_TARGET_EXT4_BLOCKSIZE=4096/#CONFIG_TARGET_EXT4_BLOCKSIZE is not set/' .config
        sed -i 's/CONFIG_TARGET_EXT4_JOURNAL=y/#CONFIG_TARGET_EXT4_JOURNAL is not set/' .config
        sed -i 's/CONFIG_ISO_IMAGES=y/#CONFIG_ISO_IMAGES is not set/' .config
        sed -i 's/CONFIG_QCOW2_IMAGES=y/#CONFIG_QCOW2_IMAGES is not set/' .config
        sed -i 's/CONFIG_VDI_IMAGES=y/#CONFIG_VDI_IMAGES is not set/' .config
        sed -i 's/CONFIG_VMDK_IMAGES=y/#CONFIG_VMDK_IMAGES is not set/' .config
        sed -i 's/CONFIG_VHDX_IMAGES=y/#CONFIG_VHDX_IMAGES is not set/' .config
        sed -i 's/CONFIG_TARGET_ROOTFS_PARTSIZE=300/CONFIG_TARGET_ROOTFS_PARTSIZE=512/' .config
        sed -i 's/CONFIG_TARGET_PREINIT_IP="192.168.1.1"/CONFIG_TARGET_PREINIT_IP="192.168.50.1"/' .config
        sed -i 's/CONFIG_TARGET_PREINIT_BROADCAST="192.168.1.255"/CONFIG_TARGET_PREINIT_BROADCAST="192.168.50.255"/' .config

    - name: æ·»åŠ éå®˜æ–¹åŒ…
      run: |
        cd immortalwrt-imagebuilder-24.10.4-x86-64.Linux-x86_64
        wget -P ./packages https://github.com/gdy666/luci-app-lucky/releases/download/v2.19.5/luci-app-lucky_2.2.2-r1_all.ipk
        wget -P ./packages https://github.com/gdy666/luci-app-lucky/releases/download/v2.19.5/luci-i18n-lucky-zh-cn_25.051.13443.e78d498_all.ipk
        wget -P ./packages https://github.com/gdy666/luci-app-lucky/releases/download/v2.19.5/lucky_2.19.5_Openwrt_x86_64.ipk
        wget -P ./packages https://github.com/tty228/luci-app-wechatpush/releases/download/v3.6.10/luci-app-wechatpush_3.6.10_all.ipk
        wget -P ./packages https://github.com/tty228/luci-app-wechatpush/releases/download/v3.6.10/luci-i18n-wechatpush-zh-cn_git-25.089.39732-ed90c03_all.ipk
        wget -P ./packages https://github.com/xiaorouji/openwrt-passwall/releases/download/25.12.1-1/luci-app-passwall_25.12.1-r1_all.ipk
        wget -P ./packages https://github.com/xiaorouji/openwrt-passwall/releases/download/25.12.1-1/luci-i18n-passwall-zh-cn_25.12.1_all.ipk
        wget -P ./packages https://github.com/xiaorouji/openwrt-passwall/releases/download/25.12.1-1/passwall_packages_ipk_x86_64.zip
        unzip ./packages/passwall_packages_ipk_x86_64.zip -d ./packages/
        wget -P ./packages https://github.com/sbwml/luci-app-mosdns/releases/download/v5.3.3-r5/openwrt-24.10-x86_64.tar.gz
        tar --strip-components=1 -xzf ./packages/openwrt-24.10-x86_64.tar.gz -C ./packages/
        wget -P ./packages https://github.com/stackia/rtp2httpd/releases/download/v3.5.2/rtp2httpd_3.5.2-r1_x86_64.ipk
        wget -P ./packages https://github.com/stackia/rtp2httpd/releases/download/v3.5.2/luci-app-rtp2httpd_3.5.2-r1_all.ipk
        wget -P ./packages https://github.com/stackia/rtp2httpd/releases/download/v3.5.2/luci-i18n-rtp2httpd-zh-cn_3.5.2_all.ipk

        
    - name: ç¼–è¯‘
      id: compile
      run: |
        cd immortalwrt-imagebuilder-24.10.4-x86-64.Linux-x86_64
        make image PACKAGES="qemu-ga pppoe-discovery bind-host luci-i18n-smartdns-zh-cn luci-i18n-package-manager-zh-cn luci-app-openclash luci-app-ddns-go luci-i18n-zerotier-zh-cn luci-i18n-ttyd-zh-cn luci-i18n-attendedsysupgrade-zh-cn luci-i18n-ddns-zh-cn ddns-scripts-dnspod luci-i18n-upnp-zh-cn luci-i18n-firewall-zh-cn luci-i18n-vlmcsd-zh-cn luci-i18n-arpbind-zh-cn luci-i18n-base-zh-cn luci-i18n-passwall-zh-cn ddns-scripts-cloudflare ddns-scripts_aliyun  luci-i18n-udpxy-zh-cn  luci-i18n-ddns-go-zh-cn luci-i18n-watchcat-zh-cn luci-app-wechatpush luci-i18n-wechatpush-zh-cn luci-i18n-wol-zh-cn luci-i18n-homeproxy-zh-cn luci-proto-wireguard luci-i18n-dashboard-zh-cn luci-i18n-timewol-zh-cn kmod-nft-socket xray-core geoview luci-app-mosdns luci-i18n-mosdns-zh-cn luci-app-lucky luci-i18n-lucky-zh-cn luci-i18n-uhttpd-zh-cn luci-i18n-rtp2httpd-zh-cn"
        echo "FILE_DATE=$(date +"%Y%m%d-%H%M")" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: æ•´ç†æ–‡ä»¶
      id: organize
      run: |
        cd immortalwrt-imagebuilder-24.10.4-x86-64.Linux-x86_64/bin/targets/*/*
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: ä¸Šä¼ firmwareæ–‡ä»¶å¤¹
      uses: actions/upload-artifact@v4
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: imagebuilder-24.10.4-x64-${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}
        
    - name: åˆ›å»º release æ ‡ç­¾
      id: tag
      run: |
        echo "release_tag=imagebuilder24.10.4-x64-${{ env.FILE_DATE }}" >> $GITHUB_OUTPUT
        touch release.txt
        echo " âï¸ imagebuilderç¼–è¯‘ä¿¡æ¯" >> release.txt
        echo "Immortalwrt-24.10.4-x64" >> release.txt
        echo "ğŸ”—https://downloads.immortalwrt.org/releases/24.10.4/targets/x86/64/" >> release.txt
        echo "â°ç¼–è¯‘å®Œæˆæ—¶é—´ï¼š$(date "+%Yå¹´%mæœˆ%dæ—¥%Hæ—¶%Måˆ†")" >> release.txt
        echo "TIME2=$(date "+%Yå¹´%mæœˆ%dæ—¥%Hæ—¶%Måˆ†")" >> $GITHUB_ENV        
        echo "status=success" >> $GITHUB_OUTPUT

    - name: ä¸Šä¼ å‘å¸ƒrelease
      uses: softprops/action-gh-release@v2
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TRIGGER_PAT }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
        
    - name: åˆ é™¤è¿è¡Œçš„å·¥ä½œæµ
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        retain_days: 5
        keep_minimum_runs: 3

    - name: åˆ é™¤æ—§Releases
      uses: ophub/delete-releases-workflows@main
      with:
        delete_releases: true
        releases_keep_latest: 12
        delete_workflows: true
        workflows_keep_day: 7
        delete_tags: true
        gh_token: ${{ secrets.ACTIONS_TRIGGER_PAT }}


               
    - name: Pushplusæ¨é€é€šçŸ¥
      if: steps.tag.outputs.status == 'success' && !cancelled()
      run: curl http://www.pushplus.plus/send -X POST -H "Content-Type:application/json" -d '{"title":"imagebuilderç¼–è¯‘immortalwrt-24.10.4-64æˆåŠŸï¼","content":" ä»${{ env.TIME1 }}å¼€å§‹åˆ°${{ env.TIME2 }}ç¼–è¯‘å®Œæˆï¼","token":"${{ secrets.PUSHPLUS_TOKEN }}","webhook":"02","channel":"cp"}'
